# Generated by Django 6.0 on 2025-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('washing', 'Washing'), ('completed', 'Completed'), ('collected', 'Car Collected')], default='pending', max_length=20),
        ),
    ]
